---
- name: Install tstdebian2
  hosts: localhost
  become: true
  vars:
    vm:
      hostname:
        tstdebian12
      ip_address:
        192.168.122.3/24
  pre_tasks:
    - name: Load the vm template
      include_vars: debian_12_vm_template.yml
    - name: display qemu_img
      debug:
        msg: 
          - 'qemu_img: {{ qemu_img }}'
  roles:
    - stafwag.virt_install_vm
